# Generated by Django 3.1.5 on 2021-02-02 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='2', max_length=15),
        ),
    ]
